### ISSUE TITLE
Instructions URL is broken

### ISSUE THREAD

**Issue by mertyildiran** [paymentwall/module-prestashop#4]
**instructions** (https://www.paymentwall.com/en/documentation/Prestashop/828) URL given in README.md is broken.

**Comment by miatran** [comment]
Hi @mertyildiran,

Sorry for the inconvenience, the URL was taken down as we are restructuring our document. Alternatively, you can take a look at https://paymentwall.github.io/modules/PrestaShop or contact our devsupport@paymentwall.com if you have any issue.

Best,
Paymentwall team
